{% set name = "blik" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blik-{{ version }}.tar.gz
  sha256: 05ef8f1f902c5c2b0e6f442baa7d336107c8434bdd4e017403d54a8d049e3050

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - cryohub >=0.5.1
    - cryotypes >=0.2.0
    - dask-core
    - einops
    - magicgui >=0.4.0
    - morphosamplers >=0.0.5
    - napari
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-image  # Not listed as requirement
    - scipy

test:
  imports:
    - blik
    - blik.reader
    - blik.utils
    - blik.writer
    - blik.widgets.file_reader
    - blik.widgets.filter
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/blik
  summary: Python tool for visualising and interacting with cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/gutsche-lab/blik

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
